config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'agencies#index_of_agencies'
  get '/:agency', to: 'agencies#list_routes_for_agency', as: 'agencies'
  get '/:agency/:code', to: 'agencies#route_no_direction', as: 'stops'

end

app/models/main.rb
class Main < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController

	#Choose an agency from a real-time list of running agencies
	def index_of_agencies
		@raw_xml_agencies = RestClient.get("http://services.my511.org/Transit2.0/GetAgencies.aspx", :params => {:token => ENV['511_KEY']})
		@agencies_list = Hash.from_xml(@raw_xml_agencies)
	end

	def list_routes_for_agency
		@raw_xml_routes = RestClient.get("http://services.my511.org/Transit2.0/GetRoutesForAgency.aspx", :params => {:token => ENV['511_KEY'], :agencyName => params[:agency]})
		@agency_route_results = Hash.from_xml(@raw_xml_routes)

		# if @agency_route_results["RTT"]["AgencyList"]["Agency"]["HasDirection"] == "True"
		# 	route_with_direction(APICall)
		# elsif @agency_route_results["RTT"]["AgencyList"]["Agency"]["HasDirection"] == "False"
		# 	route_no_direction(APICall)
		# # TODO find out how many/ what directions are used by each route with a direction
		# else
		# 	puts "ERROR!"
		# end
	end

	def route_no_direction
		@raw_xml_stops_no_d = RestClient.get("http://services.my511.org/Transit2.0/GetStopsForRoute.aspx", :params => {:token => ENV['511_KEY'], :routeIDF => "#{params[:agency]}~#{params[:code]}"})
		@stops_no_d = Hash.from_xml(@raw_xml_stops_no_d)
		# redirect to route_no_direction.html.erb?
		# binding.pry
	end

	def route_with_direction
		# TODO Dig into hash and get RouteDirection => [{"Code" => "South"}, {"Code" => "North"}]
		# TODO Display names and ask for user to choose a directional route
		@raw_xml_stops_no_d = RestClient.get("http://services.my511.org/Transit2.0/GetStopsForRoute.aspx", :params => {:token => ENV['511_KEY'], :routeIDF => "#{params[:agency]}~#{params[:code]}~params[:]"})
	end
end
# http://services.my511.org/Transit2.0/GetStopsForRoute.aspx?token=123-456- 789&routeIDF=AgencyName~RouteCode~RouteDirectionCode.

app/controllers/agency_routes_controller.rb
class AgencyRoutesController < ApplicationController


	def index
		# Manually encode the params to avoid errors with spaces and such.
		@raw_xml = RestClient.get("http://services.my511.org/Transit2.0/GetRoutesForAgency.aspx", :params => {:token => ENV['511_KEY'], :agencyName => params[:agency]})
		@route_results = Hash.from_xml(@raw_xml)
	end

	def stops
		@stops = RestClient.get("http://services.my511.org/Transit2.0/GetStopsForRoute?.aspx", :params => {:token => ENV['511_KEY'], :routeIDF => params[:agency], :routeCode => params[:code]})
		# TODO stops for routes use route code and direction
		# TODO check to see how to pull "route name" and "direction code" from params
		# TODO error checking for routes that have a direction OR just choose a single agency to work with
	end

	def choose_direction
		# TODO only present this choice if the route has a direction
		# TODO grab different params based on direction chosen OR capture first param and pass to next method
		@user_route = #RestClientCall with :routeCode?
		if @user_route["HasDirection"] == True # TODO check for string or literal boolean
			# TODO do a console API call to see how the direction param affects the results
			# TODO send to show page for choosing direction
		else
			# TODO send to index page for routes with this agency
		end
	end

	def start_stop_station
		# TODO User can pick a start and stop station and get all departing options
	end

	def times
		# TODO User can pick a date/ time and get all running services?
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Welcome to A1Transit"
			sign_user @user
			redirect_to @user
		else
			flash[:error] = "Failed to create account. Please try again."
			redirect_to new_user_path
		end

	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password)
			
		end

end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/agency_routes_helper.rb
module AgencyRoutesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/agencies/index_of_agencies.html.erb
<!-- Lists all agencies running as a link -->
<p> List of Available Agencies </p>

    <!-- Display the agency names and pass to params hash -->
    <% @agencies_list["RTT"]["AgencyList"]["Agency"].each do |agency| %>
      <div class="row">
        <%= link_to agency["Name"], agencies_path(agency["Name"]) %>
      </div>
    <% end %>


<!-- NOTES: link_to "Title", new_my_service_path(:account_id => http://acct.id) -->

app/views/agencies/list_routes_for_agency.html.erb
<!-- Shows the routes for a specific agency as links -->

<p> List of Routes for <%= "#{params[:agency]}" %> </p>

<% @agency_route_results["RTT"]["AgencyList"]["Agency"]["RouteList"]["Route"].each do |route| %>
  <div class="row">
   <!-- Want "route code" sent to params hash and "route name" displayed as link title -->
   <!-- BART "Name" is empty error check for this -->
   <%= link_to route["Name"], stops_path(@agency_route_results["RTT"]["AgencyList"]["Agency"]["Name"], route["Code"]) %>
  </div>
<% end %>

app/views/agencies/route_no_direction.html.erb
<p> List of stops for <%= "#{params[:agency]}" %> on </p>

<% @stops_no_d["RTT"]["AgencyList"]["Agency"]["RouteList"]["Route"].each do |stop| %>
  <div class="row">
   <!-- Want "route code" sent to params hash and "route name" displayed as link title -->
   <!-- BART "Name" is empty error check for this -->

   <%= link_to stop[1], stops_path(@stops_no_d["RTT"]["AgencyList"]["Agency"]["RouteList"]["Route"]["Name"], @stops_no_d["RTT"]["AgencyList"]["Agency"]["RouteList"]["Route"]["Code"]) %>

  </div>
<% end %>

app/views/agency_routes/show.html.erb
<p> List </p>

<% @code_results["RTT"]["AgencyList"]["Agency"]["RouteList"]["Route"][:code].each do |route| %>
  <div class="row">
   <!-- Want "route code" sent to params hash and "route name" displayed as link title -->

   <%= link_to route["Name"], agency_routes_path(:route => route["Code"]) %>

  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A1Transit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>

<%= yield %>

</body>
</html>